export const TEXTS = {
    TITLE: '제목:',
    DESCRIPTION: '내용:',
    LOCATION: '위치:',
    START_TIME: '시작 시간:',
    END_TIME: '종료 시간:',
    TODAY: '오늘',
    DELETE_MSG: '일정을 삭제하시겠습니까?',
    DELETE: '삭제',
    MODIFY: '수정',
    CLOSE: '닫기',
    CALL_OFF: '취소',
    SAVE: '저장',
    NEW_EVENT: '새로운 일정',
    NO_TITLE: '제목 없음',
    NO_DESCRIPTION: '내용 없음',
    NO_LOCATION: '장소 없음',
    SHOW_EVENT: '일정 상세보기',
    SHOW_EVENT_MODIFY: '일정 수정',
    CALENDAR: '캘린더',
    TODO: '할 일',
    HABBIT: '습관',
    SOMEDAY: '언젠가',
    INITIAL_PAGE_TITE: '시작 페이지',
    INITIAL_PAGE_DESCRIPTION: '사이드 메뉴 > 캘린더',

}